function [ypred] = predict(theta, y, u, param, pow, initVal)
% One step ahead prediction based on previously real outputs
%
% pow - the powers generated by the function generatePowers; we moved the
% generateion of powers outside this function in order to improve the
% running time by avoiding multiple calls to generatePowers
%
% param = [na, nb, nk]
% initVal - the initial value y1
    
    dval = [-arxform(y', param(1), 1, initVal), arxform(u', param(2), param(3), u(1))];
    pdval = regressor(dval, pow);
    ypred = pdval*theta;
end