function [regr] = regressor(d, pow)
% computes the regressor matrix; d is a matrix in the arx form and pow are
% the powers generated by generatePowers; we moved the
% generateion of powers outside this function in order to improve the
% running time by avoiding multiple calls to generatePowers
%
% the regressor is computed by rising the column elements to the respective
% power and multiplying those elements together
% for example: d = [y(k-1) u(k-1)] (na=nb=1)
% and pow = [0 1;
%            1 0;
%            1 1;
%            2 0;
%            0 2]                   (m=2)
% then the regressor matrix will be equal to
% regr = [ u(k-1) y(k-1) y(k-1)*u(k-1) y(k-1)^ 2 u(k-1)^2 ] 
         

    cases = length(pow);
    regr = ones(length(d(:,1)),cases);
    
    for i = 1:cases % To investigate parfor
        regr(:, i) = prod(d.^double(pow(i,:)),2);
    end
end
