function [theta] = train(y,u, param, pow)
% Train the model
%
% pow - the powers generated by the function generatePowers; we moved the
% generateion of powers outside this function in order to improve the
% running time by avoiding multiple calls to generatePowers
%
% param = [na, nb, nk]

    d = [-arxform(y', param(1), 1, y(1)), arxform(u', param(2), param(3), u(1))];
    pd = regressor(d, pow); 
    theta = pd\y;

end